version: 0.1.{build}-{branch}

os:
  - Visual Studio 2015

branches:
  only:
    - develop

configuration:
  - Release

install:
  - cmake --version

before_build:
  - cd ..
  - mkdir build
  - cmake -Htrial-protocol -Bbuild -G "Visual Studio 15"
  - cd build
