version: 0.1.{build}-{branch}

os:
  - Visual Studio 2015

branches:
  only:
    - develop

configuration:
  - Release

environment:
  BOOST_ROOT: C:\Libraries\boost_1_63_0

install:
  - cmake --version

before_build:
  - cd ..
  - mkdir build
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
  - cmake -Htrial-protocol -Bbuild -G "Visual Studio 14 2015 Win64" -DBOOST_ROOT="%BOOST_ROOT%"
  - cd build
